### ISSUE TITLE
Plugin launch error

### ISSUE THREAD

**Issue by hilltty** [DasSharkk/AdvancedInvisibleItemframes#2]
The server is running Purpur 1889
```
[10:21:48] [Server thread/INFO]: [AdvancedInvisibleItemframes] Enabling AdvancedInvisibleItemframes v1.0
[10:21:48] [Server thread/ERROR]: Error occurred while enabling AdvancedInvisibleItemframes v1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: me/dasshark/advancedInvisibleItemframes/metrics/Metrics
	at me.dasshark.advancedInvisibleItemframes.Main.onEnable(Main.kt:33) ~[AdvancedInvisibleItemframes-1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1888]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1888]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1888]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1888]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:338) ~[purpur-1.19.3.jar:git-Purpur-1888]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1888]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1888]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.dasshark.advancedInvisibleItemframes.metrics.Metrics
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 12 more
[10:21:48] [Server thread/INFO]: [AdvancedInvisibleItemframes] Disabling AdvancedInvisibleItemframes v1.0
```

**Comment by DasSharkk** [comment]
I'll publish a fix in a few hours, thanks vor reporting it

**Comment by DasSharkk** [comment]
@hilltty You can download the new version here: https://github.com/DasSharkk/AdvancedInvisibleItemframes/releases/tag/release-1.1

**Comment by hilltty** [comment]
thanks for your work <3
